# Spring Data
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:example-app}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=io.vhs.data.jpa.config.VhsPostgresDialect

# File uploading
spring.servlet.multipart.enabled=false

# Log pattern
logging.pattern.console=%d{dd.MM.yyyy HH:mm:ss.SSS} %clr(%-5p) [%c{0}.%M:%L] %m%n

# Session
server.servlet.session.persistent=true